### PR TITLE
fix mod

### LINKED ISSUE #53: `__mod__` can return incorrect results
Ouch -- `__abs__` was a mistake, imho. We should add the divisor instead if the result is negative.

_Originally posted by @hameerabbasi in https://github.com/willow-ahrens/finch-tensor/issues/51#issuecomment-2116987378_

### PR DESCRIPTION
**Pull request by willow-ahrens**
fixes https://github.com/willow-ahrens/finch-tensor/issues/53

### CODE REVIEW

**Review by hameerabbasi — APPROVED** [review]
Thanks for the lightning quick fix, @willow-ahrens!

**Comment by hameerabbasi** [comment]
Minor comment: Could we add a regression test?

**Comment by willow-ahrens** [comment]
Is this not tested in the array api tests?

**Comment by willow-ahrens** [comment]
I'll be fairly busy the next couple of weeks, so I'd appreciate help on these tests.

**Review by mtsokol — APPROVED** [review]

**Comment by mtsokol** [comment]
I added a regression test. Thanks @willow-ahrens!

**Pull request merged**
